# config/packages/nelmio_api_doc.yaml
nelmio_api_doc:
    documentation:
        info:
            title: "API Documentation"
            description: "Документация API"
            version: "1.0.0"
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)
        host_patterns: # document only routes with a host of the form api.*
            - ^api\.
    models:
        names:
            - { alias: Client, type: App\Entity\Client }
    html_config:
        swagger_ui_config:
            displayOperationId: true
            displayRequestDuration: true
            defaultModelsExpandDepth: 2
            defaultModelExpandDepth: 2

