<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250301205809 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, surname VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, age INT NOT NULL, ssn VARCHAR(11) NOT NULL, address VARCHAR(255) NOT NULL, fico_rating INT NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(255) NOT NULL, salary INT NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C74404557EE6971 ON client (ssn)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C7440455E7927C74 ON client (email)');
        $this->addSql('CREATE TABLE client_credits (client_id INT NOT NULL, credit_id INT NOT NULL, PRIMARY KEY(client_id, credit_id))');
        $this->addSql('CREATE INDEX IDX_132A950319EB6921 ON client_credits (client_id)');
        $this->addSql('CREATE INDEX IDX_132A9503CE062FF9 ON client_credits (credit_id)');
        $this->addSql('CREATE TABLE credit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, term INT NOT NULL, rate DOUBLE PRECISION NOT NULL, amount DOUBLE PRECISION NOT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE client_credits ADD CONSTRAINT FK_132A950319EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client_credits ADD CONSTRAINT FK_132A9503CE062FF9 FOREIGN KEY (credit_id) REFERENCES credit (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE client_credits DROP CONSTRAINT FK_132A950319EB6921');
        $this->addSql('ALTER TABLE client_credits DROP CONSTRAINT FK_132A9503CE062FF9');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE client_credits');
        $this->addSql('DROP TABLE credit');
    }
}
