controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
#api_doc:
#    path: /api/doc
#    controller: nelmio_api_doc.controller.swagger_ui
swagger_ui:
    path: /api/doc
    controller: Nelmio\ApiDocBundle\Controller\SwaggerUiController::index

#app.swagger_ui:
#    enabled: true
#    path: /api/doc
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
#app.swagger:
#    path: /api/doc.json
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger }